name: Build Launcher
on:
 pull_request:
 push:
    branches:
      - "main"

jobs:
 build:
    # Windows and Linux builds run on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [windows, linux]

    steps:
      - uses: actions/checkout@v3

      - uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.2.1
          use-dotnet: false

      - name: Verify Setup
        run: |
          godot --version

      - name: Export build
        run: |
          name="${{fromJSON('{"windows": "Windows Desktop", "linux": "Linux/X11"}')[matrix.build] }}"
          godot --headless --export-debug "$name" --verbose 2>&1 | tee build.log

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: drivechain_launcher_${{ matrix.build }}
          if-no-files-found: error
          path: build/drivechain_launcher-*
